rabbitmq:
  image: rabbitmq:management
  ports:
    - "5672:5672"
    - "15672:15672"
event-store:
  image: eventstore/eventstore
  ports:
    - "1113:1113"
    - "2113:2113"
elasticsearch:
  image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
  ports:
    - "9200:9200"
    - "9300:9300"
